joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    # Left stick Y axis is forward/backward
    axis_linear:
      x: 1
    scale_linear:
      x: 5.0
    scale_linear_turbo:
      x: 7.5

    # Right stick X axis is left/right
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 5.0
    scale_angular_turbo:
      yaw: 7.5

    # Left bumper is normal enable button
    # Right bumper is turbo enable button
    enable_button: 4
    enable_turbo_button: 5

    # "Deadman switch" for the teleop node
    # Either left or right bumper has to be held down to move
    require_enable_button: true
